### PR TITLE
Optimize UnaryStruct memory use for when its unused

### PR DESCRIPTION
**Pull request by tannewt**
Having `__init__` create a bytearray buffer costs 32 bytes for every UnaryStruct
even when its not used. This makes code size a bit larger but its
shared amongst all instances.

### CODE REVIEW

**Comment by tannewt** [comment]
Can someone review this please?

**Comment by ladyada** [comment]
hiya i dont see anything conceptually amiss here, want me to test with some i2c hardware that uses this library?

**Comment by tannewt** [comment]
@ladyada I've tested it on my end so its up to you if you want to test before approving.

**Comment by ladyada** [comment]
tested with AMG8833 - works good!

**Pull request merged**
